**Introdução a Programação + Python + Hands On**
> **Autor: Sthefanie Passo**

##**Estrutura de dados homogênea**

No mundo das estruturas de dados, conseguimos categorizá-las em dois grandes universos: **dados heterogêneos e dados homogêneos**. Nos dados homogêneas, a estrutura é composta por dados do mesmo tipo, ligados sequencialmente através de índices formarem o nosso *array*.

![alt text](https://realimoveis.net/wp-content/uploads/2018/05/PANORAMICA-525x328.png)

Usando essa associação, podemos pensar nos seguintes cenários:

* quando queremos achar uma pessoa e sabemos onde ela mora, vamos diretamente no endereço da pessoa
* quando queremos achar uma pessoa e não sabemos onde ela mora, vamos perguntando de endereço em endereço até a encontrarmos

**Sintaxe**

A nomeação de um vetor segue a mesma ideia das variáveis, com a diferença que o nome acompanha **[ ]**:

In [0]:
vetor = []
print(vetor)

[]


Os índices do vetor são formados pelo intervalo [0, N-1], onde N-1 é o tamanho do vetor menos um, ou seja, os índices de um vetor começam na posição 0 e terminam na posição N-1.
Para acessar os valores do vetor, precisamos informar em qual endereço ela está **morando**:

```
# Para acessar o valor na posicao 2, informamos o endereco nos colchetes
print(vetor[2])
```

**Percorrendo o vetor**

Como não se trata de um tipo primitivo de dado, precisamos acessar os valores de forma individual, ou seja, **se quisermos olhar todos os valores do vetor, temos que percorrê-lo, visitando índice por índice**. Como faremos isso?


Isso mesmo, **estruturas de repetição!**

```
  # forma 1
  vetor = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

  for valor in vetor:
    print(valor)

  # forma 2
  vetor = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

  for i in range(0, 10):
    print(vetor[i])
```


Exemplo: escreva um programa em Python que leia 5 valores, referentes às médias de 5 alunos. Em seguida, leia 5 números que são referentes ao número dos alunos e imprima se este aluno passou ou não na matéria (passou se a média é maior ou igual a 5).

In [0]:
notas = []
for i in range(0,5):
  notas.append(float(input("Notas: ")))
for i in range(0,5):
  if(notas[i]>=5):
    print("Congratulations student ",i)

Notas: 5
Notas: 3
Notas: 8
Notas: 10
Notas: 2
Congratulations student  0
Congratulations student  2
Congratulations student  3


Exemplo: escreva um programa em Python que leia um vetor de 10 posições e um inteiro qualquer. Calcule e imprima o produto escalar deste vetor.

In [0]:
vetor = []
escalar = int(input("Digite o escalar: "))
for i in range(0,10):
  vetor.append(int(input("Vetor: ")))
for i in range(0,10):
  vetor[i]=vetor[i]*escalar
print(vetor)

Digite o escalar: 5
Vetor: 1
Vetor: 2
Vetor: 3
Vetor: 4
Vetor: 5
Vetor: 6
Vetor: 7
Vetor: 8
Vetor: 9
Vetor: 010
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


##**Matrizes**

Vetor (array uni-dimensional) é uma variável que armazena várias variáveis do mesmo tipo. No problema apresentado anteriormente, nós podemos utilizar um vetor de 50 posições para armazenar as médias dos 50 alunos.


> Matriz (array multi-dimensional) é um vetor de vetores. No nosso problema, imagine uma matriz para armazenar as 4 notas de cada um dos 50 alunos. Ou seja, um vetor de 50 posições, e em cada posição do vetor, há outro vetor com 4 posições. Isso é uma matriz.


Cada item do vetor (ou matriz) é acessado por um número chamado de índice.

![alt text](https://informaticanaweb.files.wordpress.com/2006/11/funcao-se-img0.jpg)

Como você pode perceber nesse artigo, Vetores e Matrizes são, na verdade, a mesma coisa: array a diferença é que o vetor é um array de apenas 1 dimensão e a matriz é um array de 2 (ou mais) dimensões.

Array é uma das estruturas de dados mais simples que existe e uma das mais utilizadas também. Acho que todas as linguagens de programação têm arrays

In [3]:
vetor = [0,0,0,0]
matriz = [vetor, vetor, vetor]
matriz

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [4]:
import numpy as np

matriz1 = np.zeros((3,4), dtype=np.float64) #linha, coluna
matriz1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Escreva um programa que recebe e salva em uma matriz as notas dos 4 bimestres de 6 alunos e imprima a média de cada aluno e sua Situação escolar (Aprovado ou Reprovado).

In [5]:
notas = np.zeros((6,4), dtype=np.float64)
contas = np.zeros((6,2), dtype=np.float64) #média , situação escolar
for i in range(0,6):
  for j in range(0,4):
    print("Aluno número ", i)
    notas[i][j] = float(input("Digite a nota: "))
    contas[i][0] += notas[i][j]
  contas[i][0] = contas[i][0]/4
  if (contas[i][0] >= 5):
    contas[i][1] = 1
  else:
    contas[i][1] = 0
contas

Aluno número  0
Digite a nota: 5
Aluno número  0
Digite a nota: 4
Aluno número  0
Digite a nota: 3
Aluno número  0
Digite a nota: 2
Aluno número  1
Digite a nota: 8
Aluno número  1
Digite a nota: 8
Aluno número  1
Digite a nota: 8
Aluno número  1
Digite a nota: 8
Aluno número  2
Digite a nota: 9
Aluno número  2
Digite a nota: 4
Aluno número  2
Digite a nota: 9
Aluno número  2
Digite a nota: 10
Aluno número  3
Digite a nota: 3
Aluno número  3
Digite a nota: 4
Aluno número  3
Digite a nota: 5
Aluno número  3
Digite a nota: 6
Aluno número  4
Digite a nota: 7
Aluno número  4
Digite a nota: 8
Aluno número  4
Digite a nota: 9
Aluno número  4
Digite a nota: 10
Aluno número  5
Digite a nota: 2
Aluno número  5
Digite a nota: 3
Aluno número  5
Digite a nota: 4
Aluno número  5
Digite a nota: 8


In [6]:
contas

array([[3.5 , 0.  ],
       [8.  , 1.  ],
       [8.  , 1.  ],
       [4.5 , 0.  ],
       [8.5 , 1.  ],
       [4.25, 0.  ]])

Escreva um programa que receba quantas pessoas moram em cada casa num condominio, o condomínio possuí 7 bairros e cada bairro 5 casas. Após isso calcule a média de pessoas por casa. 

In [8]:
condominio = np.zeros((7,5), dtype=np.float64)
somaPessoa = 0
media = 0
for bairro in range(0,7):
  for casa in range(0,5):
    print("Bairro: ", bairro ,"Casa: ", casa)
    condominio[bairro][casa] = int(input("Quantas pessoas moram aqui? "))
    somaPessoa += condominio[bairro][casa]
media = somaPessoa/(bairro*casa)
print("A médias de pessoas por casa é: ", media)

Bairro:  0 Casa:  0
Quantas pessoas moram aqui? 2
Bairro:  0 Casa:  1
Quantas pessoas moram aqui? 1
Bairro:  0 Casa:  2
Quantas pessoas moram aqui? 2
Bairro:  0 Casa:  3
Quantas pessoas moram aqui? 5
Bairro:  0 Casa:  4
Quantas pessoas moram aqui? 5
Bairro:  1 Casa:  0
Quantas pessoas moram aqui? 6
Bairro:  1 Casa:  1
Quantas pessoas moram aqui? 7
Bairro:  1 Casa:  2
Quantas pessoas moram aqui? 8
Bairro:  1 Casa:  3
Quantas pessoas moram aqui? 9
Bairro:  1 Casa:  4
Quantas pessoas moram aqui? 8
Bairro:  2 Casa:  0
Quantas pessoas moram aqui? 9
Bairro:  2 Casa:  1
Quantas pessoas moram aqui? 3
Bairro:  2 Casa:  2
Quantas pessoas moram aqui? 5
Bairro:  2 Casa:  3
Quantas pessoas moram aqui? 4
Bairro:  2 Casa:  4
Quantas pessoas moram aqui? 7
Bairro:  3 Casa:  0
Quantas pessoas moram aqui? 8
Bairro:  3 Casa:  1
Quantas pessoas moram aqui? 9
Bairro:  3 Casa:  2
Quantas pessoas moram aqui? 8
Bairro:  3 Casa:  3
Quantas pessoas moram aqui? 3
Bairro:  3 Casa:  4
Quantas pessoas moram aqui? 4


In [10]:
print("%.2f", media)

%.2f 6.708333333333333


In [0]:
matriz = [[6,7,8],
          [8,8,8],
          [9,5,10]]
matriz

[[6, 7, 8], [8, 8, 8], [9, 5, 10]]

In [0]:
for i in range(0,20):
  matriz.append(int(i))
for i in range(0,20):
  matriz[i].append(int(i))
matriz.shape

AttributeError: ignored

In [0]:
casa = []
condominio = []
# for pessoas in range(0,5):
#   casa.append(int(input("Quantas pessoas tem nessa casa? ")))
for bairro in range(0,7):
  for pessoas in range(0,5):
    condominio.append[bairro](int(input("Quantas pessoas tem nessa casa? ")))
condominio

TypeError: ignored

In [0]:
import numpy as np

In [0]:
a = np.zeros((2,3), dtype=np.float64)
for bairro in range(0,2):
  for pessoas in range(0,3):
    a[bairro, pessoas] = int(input())

3
4
5
6
7
8


In [0]:
a[1:4, 1:4] = 1
a

array([[3., 4., 5.],
       [6., 1., 1.]])

In [0]:
import math
a = int(input())
b = int(input())
c = int(input())

delta = math.sqrt(b**2-4*a*c)

x1 = (-b+delta)/(2*a)
x2 = (-b-delta)/(2*a)

print("x1: ", x1)
print("x2: ", x2)

1
6
9
x1:  -3.0
x2:  -3.0


In [0]:
vetor = [5, 7, 9, 4, 10]
maior = vetor[0]
for i in range(1, 5):
  if(vetor[i]>maior):
    maior = vetor[i]

print(maior)

10


In [0]:
mediaAluno = [] #declara vetor
for aluno in range(0,10):
  mediaAluno.append(float(input("Média do Aluno: "))) #python lê como lista e não como vetor

for aluno in range(0,5):
  passou = int(input())
  if(mediaAluno[passou]>=5):
    print("O aluno",passou,"passou com",mediaAluno[passou]) #i: endereço no vetor | vet[i]: conteudo naquele endereço
  else:
    print("Tururu...")

In [0]:
#vamo ler o vetor
vetor = []

for i in range(0, 10):
  vetor.append(int(input("Digite o valor do vetor: ")))

#vamo ler o escalar
escalar = int(input("Digite o escalar: "))

#vamo fazer o produto escalar
for i in range(0,10):
  vetor[i] = vetor[i] * escalar

#vamo imprimir o vetor apos fazer o produto escalar
for i in range(0, 10):
  print(vetor[i])